# Generated by Django 5.2.17 on 2026-08-30 10:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150, unique=True)),
                ('product_company', models.CharField(blank=True, max_length=150, null=True)),
                ('opening_stock', models.IntegerField(default=0)),
                ('inward_stock', models.IntegerField(default=0)),
                ('outward_stock', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitLoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sales_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_invoice_date', models.DateField()),
                ('purchase_invoice_number', models.CharField(max_length=50, unique=True)),
                ('vendor_name', models.CharField(max_length=150)),
                ('product_name', models.CharField(max_length=150)),
                ('product_company', models.CharField(blank=True, max_length=150, null=True)),
                ('payment_term', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_invoice_date', models.DateField()),
                ('sales_invoice_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_number', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_type', models.CharField(max_length=50)),
                ('product_company', models.CharField(blank=True, max_length=150, null=True)),
                ('product', models.CharField(max_length=150)),
                ('sales_qty', models.PositiveIntegerField()),
                ('sales_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sales_net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gst_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('sales_gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warranty_days', models.PositiveIntegerField(default=0)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=150)),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendor_phone', models.CharField(max_length=20)),
                ('vendor_address', models.TextField(blank=True, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
